load("//bzl/tools/python:defs.bzl", "py_library")

py_library(
    name = "moist_growth",
    srcs = [
        "moist_growth_matrix.py",
    ],
    deps = [
        "@pypi//numpy",
        "@pypi//scipy",
    ],
) 